### ISSUE TITLE
Perform Unit Testing

### ISSUE THREAD

**Issue by Jwondr** [Jwondr/Library-Online#7]
Write test cases for admin login, book management, and user registration modules.

**Comment by Nssel** [comment]
Admin Login Module
 Test Case 1: Successful Admin Login
Description: Verify that admin can log in with valid credentials.
Steps:
  1. Open the admin login page.
  2. Enter valid username and password.
  3. Click on the login button.
Expected Result: Admin is redirected to the dashboard.

Test Case 2: Invalid Credentials
Description: Verify that login fails with invalid credentials.
Steps:
  1. Open the admin login page.
  2. Enter invalid username and/or password.
  3. Click on the login button.
Expected Result: Error message "Invalid username or password" is displayed.

Test Case 3: Empty Fields
Description: Verify that login fails when username or password fields are empty.
Steps:
  1. Open the admin login page.
  2. Leave the username or password field empty.
  3. Click on the login button.
Expected Result: Error message "Username and password are required" is displayed.

Book Management Module
 Test Case 1: Add New Book
Description: Verify that a new book can be added.
Steps:
  1. Go to the book management page.
  2. Click on the "Add New Book" button.
  3. Fill in the book details (title, author, genre, etc.).
  4. Click on the "Save" button.
Expected Result: The new book is added to the list and displayed on the book management page.
Test Case 2: Edit Book Details
Description: Verify that book details can be edited.
Steps:
  1. Go to the book management page.
  2. Select a book from the list.
  3. Click on the "Edit" button.
  4. Modify the book details.
  5. Click on the "Save" button.
Expected Result: The changes are saved, and the updated book details are displayed.

Test Case 3: Delete Book
Description: Verify that a book can be deleted.
Steps:
  1. Go to the book management page.
  2. Select a book from the list.
  3. Click on the "Delete" button.
  4. Confirm the deletion.
Expected Result: The book is removed from the list.

User Registration Module
Test Case 1: Successful User Registration
Description: Verify that a new user can register with valid details.
Steps:
  1. Open the user registration page.
  2. Enter valid user details (name, email, password, etc.).
  3. Click on the "Register" button.
Expected Result: User account is created, and a confirmation message is displayed.

Test Case 2: Duplicate Email
Description: Verify that registration fails if the email is already in use.
Steps:
  1. Open the user registration page.
  2. Enter a duplicate email.
  3. Fill in other details.
  4. Click on the "Register" button.
Expected Result: Error message "Email is already in use" is displayed.

Test Case 3: Invalid Email Format
Description: Verify that registration fails with an invalid email format.
Steps:
  1. Open the user registration page.
  2. Enter an invalid email format.
  3. Fill in other details.
  4. Click on the "Register" button.
Expected Result: Error message "Invalid email format" is displayed.
